### ISSUE TITLE
Error thrown - utils.js:

### ISSUE THREAD

**Issue by victorypoint** [SamuelBolduc/crashplan-logs#1]
I was super excited to find this and get it installed on my Synology NAS which is running a linux Crashplan client. After successfully running npm, I get this error during execute:

npm i -g crashplan-logs
/usr/local/bin/crashplan-logs -> /usr/local/lib/node_modules/crashplan-logs/app.js
+ crashplan-logs@1.0.3
added 6 packages from 14 contributors in 3.249s

crashplan-logs /volume1/docker/crashplan/config/log
Reading and parsing logfile...
internal/fs/utils.js:230
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:524:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/crashplan-logs/app.js:56:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

Any help resolving is greatly appreciated.

**Comment by SamuelBolduc** [comment]
Usually this error happens when you try to read a file but provide a directory as a path. What I think is happening here is that the custom path you're providing (`/volume1/docker/crashplan/config/log`) is a directory and not the actual log file. Look in that directory and see if you have a file named something like `backup_files.log.0`. Then try to provide the full path to this file as the command-line argument, eg. `/volume1/docker/crashplan/config/log/backup_files.log.0`.

Hopefully this fixes it!

**Comment by victorypoint** [comment]
Yes, that was it! Thank-you. Excellent viewer.

crashplan-logs -f /volume1/docker/crashplan/config/log/backup_files.log.0

**Comment by SamuelBolduc** [comment]
You're welcome! I haven't used it in a while - glad it still works!
